before:
  hooks:
    - go mod tidy
builds:
  - id: wof-sqlite-index-features
    main: ./cmd/wof-sqlite-index-features
    binary: wof-sqlite-index-features
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
universal_binaries:
  - replace: true
archives:
  -
    format: binary
    replacements:
      386: 32bit
      amd64: 64bit
      darwin: macos
      all: universal
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
